-- AlterTable
ALTER TABLE `Business` ADD COLUMN `landingTheme` ENUM('MINIMAL', 'TROPICAL', 'ELEGANTE', 'VIBRANTE', 'BOUTIQUE') NOT NULL DEFAULT 'MINIMAL';

-- AlterTable
ALTER TABLE `MenuItem` ADD COLUMN `featured` BOOLEAN NOT NULL DEFAULT false;
