-- AlterTable
ALTER TABLE `Registration` ADD COLUMN `industry` ENUM('RESTAURANTES', 'CAFETERIAS', 'BARBERIAS', 'HOTELES', 'GIMNASIOS', 'TIENDAS', 'OTRO') NULL;

-- AlterTable
ALTER TABLE `Business` ADD COLUMN `industry` ENUM('RESTAURANTES', 'CAFETERIAS', 'BARBERIAS', 'HOTELES', 'GIMNASIOS', 'TIENDAS', 'OTRO') NULL;
